<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="DESKTOP-OD6TJ4Q" name="com.CallHippo.Dialer.Calling.TeamCallingTest" tests="4" failures="0" timestamp="10 Aug 2020 14:21:50 GMT" time="764.813" errors="0">
  <testcase name="Team_FixedOrder_Outgoing_Rejected_Incoming_Reject_By_Both_Users" time="420.333" classname="com.CallHippo.Dialer.Calling.TeamCallingTest">
    <skipped/>
  </testcase> <!-- Team_FixedOrder_Outgoing_Rejected_Incoming_Reject_By_Both_Users -->
  <testcase name="Team_FixedOrder_Outgoing_Rejected_Incoming_Reject_By_Both_Users" time="187.088" classname="com.CallHippo.Dialer.Calling.TeamCallingTest"/>
  <testcase name="Team_FixedOrder_Outgoing_Rejected_Incoming_Reject_By_Both_Users" time="157.392" classname="com.CallHippo.Dialer.Calling.TeamCallingTest">
    <skipped/>
  </testcase> <!-- Team_FixedOrder_Outgoing_Rejected_Incoming_Reject_By_Both_Users -->
  <testcase name="Outgoing_Completed_Incoming_Answered_By_Main_user_and_Sub_User_is_busy_with_ongoingCall" classname="com.CallHippo.Dialer.Calling.TeamCallingTest">
    <skipped/>
  </testcase> <!-- Outgoing_Completed_Incoming_Answered_By_Main_user_and_Sub_User_is_busy_with_ongoingCall -->
</testsuite> <!-- com.CallHippo.Dialer.Calling.TeamCallingTest -->
